version: '3.9'

services:
  landing_dev:
    container_name: landing_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.development
    ports:
      - '5173:5173'
